name: Production Monitoring

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Check production health
        run: |
          # Check main health endpoint
          HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://devpulse.vercel.app/api/health)
          
          if [ "$HEALTH_STATUS" != "200" ]; then
            echo "❌ Health check failed with status: $HEALTH_STATUS"
            exit 1
          else
            echo "✅ Health check passed"
          fi
          
      - name: Check API endpoints
        run: |
          # Test critical API endpoints
          ENDPOINTS=(
            "/api/auth/session"
            "/api/analytics/burnout"
            "/api/github/repositories"
          )
          
          for endpoint in "${ENDPOINTS[@]}"; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://devpulse.vercel.app$endpoint")
            if [ "$STATUS" = "401" ] || [ "$STATUS" = "200" ]; then
              echo "✅ $endpoint: $STATUS (expected)"
            else
              echo "❌ $endpoint: $STATUS (unexpected)"
              exit 1
            fi
          done
          
      - name: Performance check
        run: |
          # Check response time
          RESPONSE_TIME=$(curl -s -o /dev/null -w "%{time_total}" https://devpulse.vercel.app)
          THRESHOLD=3.0
          
          if (( $(echo "$RESPONSE_TIME > $THRESHOLD" | bc -l) )); then
            echo "❌ Response time too slow: ${RESPONSE_TIME}s (threshold: ${THRESHOLD}s)"
            exit 1
          else
            echo "✅ Response time OK: ${RESPONSE_TIME}s"
          fi
          
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Production Health Check Failed',
              body: `## Production Health Check Failed
              
              **Time:** ${new Date().toISOString()}
              **Workflow:** ${context.workflow}
              **Run ID:** ${context.runId}
              
              ### Details
              The production health check has failed. Please investigate immediately.
              
              ### Actions Required
              1. Check production logs
              2. Verify service status
              3. Check external dependencies
              4. Consider rollback if necessary
              
              ### Links
              - [Failed workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId})
              - [Production URL](https://devpulse.vercel.app)
              `,
              labels: ['bug', 'production', 'urgent']
            });

  uptime-check:
    name: Uptime Monitoring
    runs-on: ubuntu-latest
    
    steps:
      - name: Check uptime
        uses: upptime/uptime-monitor@v1
        with:
          command: "curl"
          url: "https://devpulse.vercel.app"
          expected-status-codes: "200"
          
      - name: Log uptime status
        run: |
          echo "Uptime check completed at $(date)"
          
  lighthouse-monitoring:
    name: Performance Monitoring
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
        
      - name: Run Lighthouse audit
        run: |
          lhci collect --url=https://devpulse.vercel.app
          lhci assert
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30